const SERVER_PORT = 8081;
const ROWS = 4;
const COLUMNS = 5;
const SYMBOL_TEXTURE_COUNT = 11;
const REEL_POSITIONS = [0, 130, 260, 390, 520];

module.exports = {
  SERVER_PORT,
  ROWS,
  COLUMNS,
  SYMBOL_TEXTURE_COUNT,
  REEL_POSITIONS,
};
